### ISSUE TITLE
Add support for disk-based emptyDir volumes

### ISSUE THREAD

**Issue by jonnymatts-global** [gruntwork-io/helm-kubernetes-services#105]
We would like to create and use `emptyDir` volumes that are backed by disk. #91 added the ability to create `emptyDir` volumes as `scratchPaths`, however the implementation is hard-coded to use tmpfs via the `medium: "Memory"` option provided to the `emptyDir` spec.

What would be the best way to approach adding support for disk-based `emptyDir`s?

**Comment by bitbrain** [comment]
Is there an ETA by when this will be released? We are depending on this feature.
