### ISSUE TITLE
Support Vertical Pod Autoscalers

### ISSUE THREAD

**Issue by reynoldsme** [gruntwork-io/helm-kubernetes-services#162]
**Describe the solution you'd like**
It would be great to have support for Vertical Pod Autoscalers (VPAs) in the k8s-service module just like horizontal pod autoscalers are supported today.

**Describe alternatives you've considered**
The only alternative would be to manage the VPA as a separate object, which while possible, feels like it deviates from the Gruntwork model.

**Additional context**
https://github.com/kubernetes/autoscaler/tree/master/vertical-pod-autoscaler
https://docs.aws.amazon.com/eks/latest/userguide/vertical-pod-autoscaler.html

**Comment by pras111gw** [comment]
Hi @reynoldsme thank you for submitting the request. I didn't see VPA support in terraform resources, but we will review adding VPA in our eks modules soon.
