### ISSUE TITLE
Support Scaling policies for HPAs

### ISSUE THREAD

**Issue by reynoldsme** [gruntwork-io/helm-kubernetes-services#163]
**Describe the solution you'd like**
the k8s-service module supports creating Horizontal Pod Autoscalers for Deployments created by the module. It would be helpful to be able to configure Scaling policies that control the speed of scale up and scale down events.

**Describe alternatives you've considered**
The only other option would be to stop using the built in HPA support, and manage HPAs via a different module.

**Additional context**
https://kubernetes.io/docs/tasks/run-application/horizontal-pod-autoscale/#scaling-policies

**Comment by ryehowell** [comment]
Hi @reynoldsme, thanks for opening this Issue! Apologies for the delayed attention to this. I just opened a PR that addresses this Issue. Please take a look at it and keep an eye on it for the next release.
