### ISSUE TITLE
Latest releases are not present in the repository

### ISSUE THREAD

**Issue by nadiia-caspar** [gruntwork-io/helm-kubernetes-services#168]
**Describe the bug**
The latest release in this repository has v0.2.21, but Helm cannot find it. The `helm search repo gruntwork --versions` command shows me the latest available chart version `v0.2.19`

**To Reproduce**

```shell
$ helm repo add gruntwork https://helmcharts.gruntwork.io
$ helm repo update
$ helm search repo gruntwork --versions
NAME                    CHART VERSION   APP VERSION     DESCRIPTION                                       
gruntwork/k8s-service   v0.2.19                         A Helm chart to package your application contai...
```

Helm update fails with:
```
Error: chart "k8s-service" matching v0.2.21 not found in gruntwork index. (try 'helm repo update'): no chart version found for k8s-service-v0.2.21
```

**Expected behavior**
```shell
$ helm search repo gruntwork --versions
NAME                    CHART VERSION   APP VERSION     DESCRIPTION                                       
gruntwork/k8s-service   v0.2.21                         A Helm chart to package your application contai...
```

**Nice to have**
- [x] Terminal output
- [ ] Screenshots

**Additional context**

**Comment by ryehowell** [comment]
Hi @nadiia-caspar, thank you for raising this Issue! You are correct with the releases being a couple versions behind. I've published the latest releases and they will be available soon. Once this [PR](https://github.com/gruntwork-io/helmcharts/pull/50) is merged, the latest versions will be available. This _should_ be done tomorrow at some point.

**Comment by nadiia-caspar** [comment]
@ryehowell ah, okay. thank you for the explanation

**Comment by ryehowell** [comment]
Hi @nadiia-caspar, I just wanted to follow up to let you know that the latest releases are now available. Thanks again for raising the Issue!

```sh
$ helm search repo gruntwork/k8s-service -l
NAME                 	CHART VERSION	APP VERSION	DESCRIPTION
gruntwork/k8s-service	v0.2.21      	           	A Helm chart to package your application contai...
gruntwork/k8s-service	v0.2.20      	           	A Helm chart to package your application contai...
gruntwork/k8s-service	v0.2.19      	           	A Helm chart to package your application contai...
gruntwork/k8s-service	v0.2.18      	           	A Helm chart to package your application contai...
gruntwork/k8s-service	v0.2.17      	           	A Helm chart to package your application contai...
... 
```
