### ISSUE TITLE
Deployment.spec.replicas incorrectly set when using HPA

### ISSUE THREAD

**Issue by harrymilne** [gruntwork-io/helm-kubernetes-services#180]
**Describe the bug**

When `horizontalPodAutoscaler.enabled` is set to `true` the `Deployment` `spec.replicas` value should not be set as it will cause the ReplicaSet to revert from whatever HPA is recommending. 

**To Reproduce**

1. set `horizontalPodAutoscaler.enabled` to `true`
2. deploy new version
3. watch as Pods match the `spec.replicas` rather than matching HPA

**Expected behavior**
A new deployment matches the Pods recommended by HPA

* [Kubernetes docs](https://kubernetes.io/docs/tasks/run-application/horizontal-pod-autoscale/#migrating-deployments-and-statefulsets-to-horizontal-autoscaling)
* [Stackoverflow question](https://stackoverflow.com/questions/66431556/what-is-the-relationship-between-the-hpa-and-replicaset-in-kubernetes/76548515#76548515)

**Comment by ryehowell** [comment]
Hi @harrymilne, just to close the loop on this, this issue was resolved and the fix is available in the latest release of the Helm chart `v0.2.25`. Thanks for reporting the issue and your patience on a fix!
