### ISSUE TITLE
Use 'ingressClassName' instead deprecated annotation "kubernetes.io/ingress.class"

### ISSUE THREAD

**Issue by nadiia-caspar** [gruntwork-io/helm-kubernetes-services#189]
**Describe the solution you'd like**
I've noticed the warning during a chart deployment:
```
W0612 15:00:09.676081    1973 warnings.go:70] annotation "kubernetes.io/ingress.class" is deprecated, please use 'spec.ingressClassName' instead
```

The `kubernetes.io/ingress.class` annotation is deprecated since [Kubernetes v1.18 ](https://kubernetes.io/blog/2020/04/02/improvements-to-the-ingress-api-in-kubernetes-1.18/#extended-configuration-with-ingress-classes), also a [deprecation notes in AWS load balancer](https://github.com/kubernetes-sigs/aws-load-balancer-controller/blob/e5d625f96415fd44e6399e9c75e2bd985f5a2288/docs/guide/ingress/ingress_class.md?plain=1#L40).

So we might add the `spec.ingressClassName` field to the Ingress template.

**Comment by ryehowell** [comment]
Hi @nadiia-caspar, thanks for opening this issue!

This should def be updated. We will get it into the backlog for one of the upcoming sprints. We do welcome PR's as well if you are interested in contributing an update for this 😄

**Comment by nadiia-caspar** [comment]
@ryehowell i could try to create a PR. But would need so clarification: do you support backward compatibilities? Should the previous way with annotations be supported?

**Comment by ryehowell** [comment]
Hi @nadiia-caspar, we always try to maintain as much backwards compatibility as possible, whenever and wherever possible.

**Comment by nadiia-caspar** [comment]
@ryehowell thanks for the fix, sorry, lost this issue from my radar
