### ISSUE TITLE
Allow for setting securytcontext for a container

### ISSUE THREAD

**Issue by tverhoeven** [gruntwork-io/helm-kubernetes-services#26]
We are using the k8s-service chart with great succes. But we recently stumbled on a issue. One of the container images that we need to deploy needs to run in privileged mode.

This means that we need to be able to set:
        securityContext:
          privileged: true
in the deployment record.

But currently the chart does not allow you to specifiy this or any other securityContext settings. Could this be added to the chart?

Thanks, Tim

**Comment by yorinasub17** [comment]
That's a good idea to add! We are pretty buried right now so might not get to this in the short term. Would you be up for a PR?

**Comment by shenal** [comment]
This feature has been implemented and released in v0.0.7
@yorinasub17 , @tverhoeven , @autero1 We can close this out

**Comment by autero1** [comment]
Closing, implemented in #36
