### ISSUE TITLE
Prometheus Operator CRD

### ISSUE THREAD

**Issue by stuart-c** [gruntwork-io/helm-kubernetes-services#27]
It would be useful if the chart could support the optional creation of a ServiceMonitor CRD to allow easy integration with Prometheus Operator.

Would this be something you'd consider including if a PR was created?

**Comment by yorinasub17** [comment]
Yes that sounds like a great idea!

**Comment by efernandes-ANDigital** [comment]
@yorinasub17 Hey opened a PR with regards to this. Was wondering if you could take a look. Thanks
https://github.com/gruntwork-io/helm-kubernetes-services/pull/43

**Comment by yorinasub17** [comment]
This is now in https://github.com/gruntwork-io/helm-kubernetes-services/releases/tag/v0.0.11

Will be adding to helm chart repository later, once the package is built.
