### ISSUE TITLE
Issue with required ServiceName for additional paths into Ingress resource

### ISSUE THREAD

**Issue by gueux** [gruntwork-io/helm-kubernetes-services#37]
It looks like this commit added not enough conditions to ingress resource:

https://github.com/gruntwork-io/helm-kubernetes-services/commit/5a26c586ea24b0783f6b4e6318a56afa70a0c09a

As it is still requires ServiceName definition for additionalPathsHigherPriority and additionalPaths if the `.Values.ingress.hosts` is defined:

https://github.com/gruntwork-io/helm-kubernetes-services/commit/5a26c586ea24b0783f6b4e6318a56afa70a0c09a

https://github.com/gruntwork-io/helm-kubernetes-services/commit/5a26c586ea24b0783f6b4e6318a56afa70a0c09a

**Comment by yorinasub17** [comment]
Oh yup you are right! Are you up for a quick PR? Adding a helm template test for this condition to check for regression would be good.

**Comment by yorinasub17** [comment]
This has been fixed in https://github.com/gruntwork-io/helm-kubernetes-services/releases/tag/v0.0.9
