### ISSUE TITLE
Adding a sideCarContainer gives an error about mapping values

### ISSUE THREAD

**Issue by tverhoeven** [gruntwork-io/helm-kubernetes-services#40]
I'm trying to deploy an app that is build out of 2 containers. The main app I can deploy just fine, but when I add a "sideCarContainers:" section I get an error like this:

`error: error converting YAML to JSON: yaml: line 47: mapping values are not allowed in this context`

This is the section I added, commenting this out makes the error disappear:
```
sideCarContainers:
  appengine:
    image: eu.gcr.io/our-gce-project/container-name:0.1.0
```

Deploying this container using a separate helm chart works just fine.

We use this helm chart using the Terraform helm provider. I've been trying to get more debugging information, but that has failed up to now. 

As a workaround/test I manually edited the resulting deployment yaml in GKE and added the 2nd container, and that also worked fine. 

Let me know what I can do to further debug this or what more information you require.

**Comment by yorinasub17** [comment]
This has been fixed in https://github.com/gruntwork-io/helm-kubernetes-services/releases/tag/v0.0.9
