### ISSUE TITLE
deleting k8s-service leaves route-53 records

### ISSUE THREAD

**Issue by mcalhoun** [gruntwork-io/helm-kubernetes-services#42]
When deleting the `k8s-service` via `terraform destroy` leaves the `route-53` records in place and they need to be cleaned up manually.

**Comment by yorinasub17** [comment]
The DNS records are managed in the [external-dns](https://github.com/kubernetes-incubator/external-dns) app, so this can be done if you switch to using `sync` mode for managing the records.

**Comment by yorinasub17** [comment]
Going to close this as we resolved in slack. For posterity, this isn't something we can control in the chart, and must be handled at the installation point for `external-dns`. Let me know if you still need help!
