### ISSUE TITLE
Add support for Helm 3

### ISSUE THREAD

**Issue by pgold30** [gruntwork-io/helm-kubernetes-services#47]
https://helm.sh/blog/helm-3-released/

Server side is not needed which will makes things way easrier. 
Is this version of Helm supported under this module?

**Comment by robmorgan** [comment]
hi @pgold30 not at the moment, we were waiting for Helm 3 GA to be released. Would you be up for a PR?

**Comment by pgold30** [comment]
Hi @robmorgan  Helm 3 was released 9 days ago : https://github.com/helm/helm/releases/tag/v3.0.0. 
I would be up for using it when its developed.

**Comment by robmorgan** [comment]
@pgold30 feel free to contribute something in the meantime until we get to it.

**Comment by yorinasub17** [comment]
We are now testing on helm 3 and have verified that the chart, as is, will work on helm 3 without any modifications.
