### ISSUE TITLE
support for envFrom for secrets

### ISSUE THREAD

**Issue by ecasilla** [gruntwork-io/helm-kubernetes-services#87]
This change helps avoid having to enumerate all secrets and keep the management of the secrets isolated to the secrets config and not both the secret config and the chart.

https://v1-18.docs.kubernetes.io/docs/concepts/configuration/secret/#use-case-as-container-environment-variables

**Comment by yorinasub17** [comment]
This should already be supported. See https://github.com/gruntwork-io/helm-kubernetes-services/tree/master/examples/k8s-service-config-injection#injecting-the-secret-in-to-the-application

Or are you thinking of something else?

**Comment by yorinasub17** [comment]
Released as https://github.com/gruntwork-io/helm-kubernetes-services/releases/tag/v0.2.3
Will be published to registry shortly.
